# -- Main Menu --

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "笔记"
  pageRef = "notes"
  weight = 10

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

# -- Footer Menu --

[[footer]]
  name = "关于"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "RSS"
  url = "index.xml"
  weight = 20
